In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_array', arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1 = np.load('my_array.npy')

In [8]:
arr2 = np.arange(10)

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# zip形式で保存
np.savez('ziparrays.npz', x=arr1,y=arr2)

In [15]:
archive_array = np.load('ziparrays.npz')

In [16]:
archive_array

In [17]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [18]:
np.savetxt('my_tst_text.txt', arr, delimiter=',')

In [19]:
!cat my_tst_text.txt

0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
9.000000000000000000e+00


In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])