In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#平方根計算
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
# べき乗計算  
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.99341704,  0.02819207, -2.58573896, -1.38008718,  0.17623523,
       -0.02383482, -0.0533203 ,  0.16448358,  2.17508236,  1.0498307 ])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-0.72857351,  0.15203195, -0.0405702 , -0.89764056,  0.78576446,
        0.41670915,  0.38974417,  0.66410616, -1.60249955, -1.07820085])

In [11]:
np.add(A,B)

array([ 0.26484352,  0.18022403, -2.62630916, -2.27772773,  0.96199969,
        0.39287432,  0.33642387,  0.82858974,  0.57258281, -0.02837015])

In [12]:
np.maximum(A,B)

array([ 0.99341704,  0.15203195, -0.0405702 , -0.89764056,  0.78576446,
        0.41670915,  0.38974417,  0.66410616,  2.17508236,  1.0498307 ])

### jupyter notebookのヘルプからnumpyのドキュメントが読める