In [34]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [3]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'], ' data_set_1':np.arange(6)})

In [4]:
dframe1

key   data_set_1
0   X            0
1   Z            1
2   Y            2
3   Z            3
4   X            4
5   X            5

In [5]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})

In [6]:
dframe2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [7]:
pd.merge(dframe1,dframe2)

key   data_set_1  data_set_2
0   Z            1           3
1   Z            3           3
2   Y            2           2

In [8]:
pd.merge(dframe1,dframe2,on='key')

key   data_set_1  data_set_2
0   Z            1           3
1   Z            3           3
2   Y            2           2

In [9]:
pd.merge(dframe1,dframe2,on='key',how='right')

key   data_set_1  data_set_2
0   Z          1.0           3
1   Z          3.0           3
2   Y          2.0           2
3   Q          NaN           1

In [10]:
pd.merge(dframe1,dframe2,on='key',how='outer')

key   data_set_1  data_set_2
0   X          0.0         NaN
1   X          4.0         NaN
2   X          5.0         NaN
3   Z          1.0         3.0
4   Z          3.0         3.0
5   Y          2.0         2.0
6   Q          NaN         1.0

In [11]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'],'data_set_3':range(6)})

In [12]:
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'],'data_set_4':range(5)})

In [13]:
dframe3

key  data_set_3
0   X           0
1   X           1
2   X           2
3   Y           3
4   Z           4
5   Z           5

In [14]:
dframe4

key  data_set_4
0   Y           0
1   Y           1
2   X           2
3   X           3
4   Z           4

In [15]:
pd.merge(dframe3,dframe4)

key  data_set_3  data_set_4
0   X           0           2
1   X           0           3
2   X           1           2
3   X           1           3
4   X           2           2
5   X           2           3
6   Y           3           0
7   Y           3           1
8   Z           4           4
9   Z           5           4

### Xが６行になったりするのは総当たりのため、Xが２行✖︎３行で６行になる

In [16]:
# 複数の列名に関して、mergeを使うこともできる。
df_left = DataFrame({'key1': ['SF', 'SF', 'LA'],
                  'key2': ['one', 'two', 'one'],
                  'left_data': [10,20,30]})
df_right = DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'right_data': [40,50,60,70]})
pd.merge(df_left, df_right, on=['key1', 'key2'], how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [17]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [18]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [23]:
arr1 = np.arange(9).reshape((3,3))

In [24]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# axisは列の方向
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [30]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [36]:
ser1

T    0
U    1
V    2
dtype: int64

In [37]:
ser2

X    3
Y    4
dtype: int64

In [39]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

### SeriesとDataFrameの違いを改めて。
SeriesはDataFrameの1つのカラムを指すデータ構造であり、  
DataFrame内のデータは多数のSeriesの集まりであると考えられます。  
別の捉え方をすれば、Seriesは一次元のデータ構造、DataFrameは二次元のデータ構造

#### まとめ
Seriesは一次元の、DataFrameは二次元のデータ構造であり、DataFrameはSeriesから構成される